Update aliases

diff --git a/misc/bashenv/bash_aliases b/misc/bashenv/bash_aliases
--- a/misc/bashenv/bash_aliases
+++ b/misc/bashenv/bash_aliases
@@ -16,7 +16,43 @@ function pgbuild() {
         return
     fi
     local destname="${1:-"$(basename $(pwd))"}"
-    local dest="$HOME/pg/$destname"
+    local variant="${2:-}"
+    local configure_args
+    case "${variant:-}" in
+	"")
+	    configure_args="--enable-debug --enable-cassert --enable-tap-tests --enable-dtrace"
+	    ;;
+	"NDEBUG")
+	    configure_args=""
+	    ;;
+	*)
+	    echo "unrecognised build variant $variant"
+	    return
+	    ;;
+    esac
+    local srcdir="$(pwd)"
+    local dest="$HOME/pg/$destname"${variant:+-${variant}}
+    if [ -z "$NO_VPATH" ]; then
+	local builddir=$HOME/build/$(basename "$srcdir")${variant:+${variant}}
+	if [ -z "$builddir" ]; then
+	    echo "unable to determine valid build-directory, aborting"
+	    return 1
+	else
+	    echo "Building $srcdir out-of-tree in $builddir"
+	fi
+	if [ -d "$builddir".old ]; then
+	    rm -rf "$builddir".old
+	fi
+	if [ -d "$builddir" ]; then
+	    mv "$builddir" "$builddir".old
+	fi
+	mkdir -p "$builddir";
+	local configurepath="$srcdir/configure"
+    else
+	echo "in-tree build"
+	local builddir=$srcdir
+	local configurepath="./configure"
+    fi
     if [ -z "${NO_SILENT:-}" ]
     then
 	local CONFQUIET="--quiet"
@@ -24,14 +60,36 @@ function pgbuild() {
     else
 	echo "NO_SILENT assigned, going loud"
     fi
-    echo "configuring for $dest"
-    CFLAGS="-ggdb3 -O0" ./configure $CONFQUIET --cache-file=config.cache --prefix="$dest" --enable-debug --enable-cassert --enable-tap-tests --enable-dtrace && \
-    echo "configured, making" && \
-    make $SILENT clean && \
-    make $SILENT -j4 && make $SILENT -C contrib -j4 && \
-    echo "compiled" && \
-    make $SILENT install && make $SILENT -C contrib install && \
-    echo "installed to $dest"
+    (
+    	cd $builddir
+	set -e
+	echo "configuring for $dest"
+	CFLAGS="-ggdb3 -O0" $configurepath $CONFQUIET --cache-file=config.cache --prefix="$dest" --enable-debug --enable-cassert --enable-tap-tests --enable-dtrace
+	echo "configured, making"
+	make $SILENT clean
+	make $SILENT -j4
+	make $SILENT -C contrib -j4
+	echo "compiled"
+	make $SILENT install
+	make $SILENT -C contrib install
+	echo "installed to $dest"
+    )
+    rm -f build${variant:+-${variant}}
+    ln -s $builddir build${variant:+-${variant}}
+}
+
+function pgbuildall() {
+    if [ -n "${NO_VPATH:-}" ]; then
+	echo "VO_VPATH set but cannot pgbuildall without vpath"
+	return
+    fi
+    echo "building base variant..."
+    pgbuild "$(basename $(pwd))"
+    echo "base variant built"
+    echo "building NDEBUG variant"
+    pgbuild "$(basename $(pwd))" "NDEBUG"
+    echo "NDEBUG variant built"
+    ls -d build*
 }
 
 #
@@ -82,7 +140,7 @@ function extbuild() {
 	    echo "${extgenfile} still exists in srcdir, clean vpath build not possible. Clean source dir."
 	    return 1
 	fi
-	local builddir=$(dirname "$srcdir")/$(basename "$srcdir")-build
+	local builddir=$HOME/build/$(basename "$srcdir")
 	if [ -z "$builddir" ]; then
 	    echo "unable to determine valid build-directory, aborting"
 	    return 1
@@ -114,6 +172,8 @@ function extbuild() {
 	PATH="$newpath" make $MAKEFILEARG $SILENT REGRESS_LOG_MIN_MESSAGES=debug2 PROVE_FLAGS="--verbose" "$@"
     )
     echo "rebuild and install done"
+    rm -f build
+    ln -s $builddir build
 }
 
 function pgl3build() {
@@ -176,3 +236,56 @@ PROMPT_COMMAND='__git_ps1 "\\j \\w" "\\\$ "'
 PROMPT_DIRTRIM=2
 export PROMPT_COMMAND PROMPT_DIRTRIM
 
+
+function pg() {
+    local ver=${1:-2q1136}
+    local subdir
+    case "${ver}" in
+        2[qQ]10)
+            subdir=2QREL_10_STABLE
+            ;;
+        2[qQ]11*3*6)
+            subdir=2QREL_11_STABLE_3_6
+            ;;
+        2[qQ]11*3*7|2[qQ]11)
+            subdir=2QREL_11_STABLE_dev
+            ;;
+        2[qQ]12)
+            subdir=2QREL_12_STABLE_dev
+            ;;
+        10|11|12)
+            subdir=REL_${ver}_STABLE
+            ;;
+        9*4)
+            subdir=REL9_4_STABLE
+            ;;
+        9*5)
+            subdir=REL9_5_STABLE
+            ;;
+        9*5)
+            subdir=REL9_6_STABLE
+            ;;
+        *)
+            subdir="${ver}"
+            ;;
+    esac
+    pushd ~/projects/2Q/postgres/${subdir}
+}
+
+function pgl() {
+    local subdir="${1:-master}"
+    if [ "${1:-}" == "36" ]; then
+        subdir=REL3_6_STABLE
+    fi
+    pushd ~/projects/2Q/pglogical/pglogical-${subdir}
+}
+
+function bdr() {
+    local subdir="${1:-master}"
+    if [ "${1:-}" == "36" ]; then
+        subdir=REL3_6_STABLE
+    fi
+    pushd ~/projects/2Q/bdr/bdr-${subdir}
+}
+
+# vim: ts=4 sw=4 et ai
